CREATE TABLE Cities
(
	CTY_IdCity INT PRIMARY KEY IDENTITY(1,1),
	CTY_Name NVARCHAR(100) NOT NULL
)

CREATE TABLE Users
(
	USR_IdUser INT PRIMARY KEY IDENTITY(1,1),
	USR_Name NVARCHAR(100) NOT NULL,
	USR_LastName NVARCHAR(100) NOT NULL,
	USR_Mail NVARCHAR(100) NOT NULL UNIQUE,
	USR_Password VARCHAR(MAX) NOT NULL,
	USR_CreationDate DATETIME DEFAULT GETDATE()
)

CREATE TABLE InterEvents
(
	EVT_IdEvent INT IDENTITY(1,1) PRIMARY KEY,
	EVT_EventName NVARCHAR(100) NOT NULL,
	EVT_Description NVARCHAR(MAX) NOT NULL,
	EVT_Date DATETIME NOT NULL,
	EVT_IdCity INT NOT NULL,
	EVT_Address NVARCHAR(300) NOT NULL,
	EVT_Latitude NVARCHAR(20) NOT NULL,
	EVT_Longitude NVARCHAR(20) NOT NULL,
	EVT_Capacity INT NOT NULL,
	EVT_Active BIT NOT NULL DEFAULT 1,
	EVT_IdOwner INT NOT NULL,
	EVT_CreationDate DATETIME DEFAULT GETDATE(),
	EVT_ModifyDate DATETIME,
	EVT_DeleteDate DATETIME,
	CONSTRAINT FK_Events_City FOREIGN KEY (EVT_IdCity) REFERENCES Cities(CTY_IdCity),
	CONSTRAINT FK_Events_User FOREIGN KEY (EVT_IdOwner) REFERENCES Users(USR_IdUser)
)

CREATE TABLE Attendants
(
	ATN_IdEvent INT NOT NULL,
	ATN_IdUser INT NOT NULL,
	CONSTRAINT FK_Attendants_Events FOREIGN KEY (ATN_IdEvent) REFERENCES InterEvents(EVT_IdEvent)
)

INSERT INTO Cities 
	([CTY_Name])
VALUES
	('Bogotá D.C.'),
	('Medellin'),
	('Buscaramanga'),
	('Cartagena'),
	('Cali'),
	('Santa Marta')